### ISSUE TITLE
test-kitchen version check problems

### ISSUE THREAD

**Issue by storpipfugl** [esmil/kitchen-qemu#18]
Hi,

We are now at test-kitchen 2.2 which makes https://github.com/esmil/kitchen-qemu/blob/master/kitchen-qemu.gemspec#L39 fail.

Everything seems to work fine with test-kitchen 2 and kitchen-qemu so is it possible to get a new ruby gems release of kitchen-qemu with the constraint removed (or relaxed)?

**Comment by esmil** [comment]
Yes, done.
